
export function Introduction() {
  return (
    <>
      <h2>Why MDMA?</h2>
      <p>AI conversations today are plain text — the user reads a response and manually acts on it. MDMA changes that. When an LLM knows the MDMA spec, it can respond with interactive components (forms, tables, approval gates) instead of just text. The conversation becomes actionable: the user fills out a form, approves a step, or reviews structured data — all inline, with a predictable schema that your app already knows how to render and process.</p>
      <p>No custom UI per use case. No parsing free-form text. The AI generates structured, validated components and your frontend renders them instantly.</p>

      <h2>What is MDMA?</h2>
      <p>
        MDMA is an open standard that extends Markdown with interactive UI components. Instead of
        returning plain text, an LLM can respond with a typed, schema-validated component — a form,
        a table, an approval gate — embedded directly in the conversation. Your frontend parses it,
        the runtime manages its state, and the renderer displays it. No custom parsing, no
        free-form text extraction.
      </p>
      <p>
        Components are declared in fenced <code>mdma</code> code blocks using YAML. Each block has
        a <code>type</code> and an <code>id</code>, and the rest of the fields are specific to that
        component. The spec defines 9 built-in types: <code>form</code>, <code>button</code>,{' '}
        <code>tasklist</code>, <code>table</code>, <code>chart</code>, <code>callout</code>,{' '}
        <code>approval-gate</code>, <code>webhook</code>, and <code>thinking</code>.
      </p>
      <p>
        The format is designed to be generated by LLMs. Give the model a system prompt from{' '}
        <code>mdma-prompt-pack</code> and it will produce valid, schema-conformant components. The
        parser validates every block against Zod schemas, so malformed output is caught early and
        never reaches your UI in an unpredictable state.
      </p>
      <p className="docs-intro-footnote">Made with love by <a href="https://themobilereality.com" target="_blank" rel="noreferrer">Mobile Reality</a>.</p>
    </>
  );
}
